/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpkg;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.ButtonUI;
import javax.swing.plaf.basic.BasicButtonUI;
import myCharts.BodyWashSalesChartFrame;
import myCharts.EngineSalesChartFrame;
import myCharts.FuelSalesChartsFrame;
import org.apache.commons.io.FileUtils;
/**
 *
 * @author Sadman's Den
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        jDesktopPane1.add(carWashJ);
        jDesktopPane1.add(orderJ);
        jDesktopPane1.add(salesJ);
        jDesktopPane1.add(storageJ);


        carWashJ.setVisible(false);
        orderJ.setVisible(false);
        salesJ.setVisible(false);
        storageJ.setVisible(false);
        ImageIcon myimage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("FuelLogo.png")));
        
      /* Image img1 = myimage.getImage();
       Image img2 = img1.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon i = new ImageIcon(img2);*/
        
        //jLabel1.setIcon(i);
         carWashBtn.setUI((ButtonUI) BasicButtonUI.createUI(carWashBtn));
         orderBtn.setUI((ButtonUI) BasicButtonUI.createUI(orderBtn));
         storageBtn.setUI((ButtonUI) BasicButtonUI.createUI(storageBtn));
         salesDetailsBtn.setUI((ButtonUI) BasicButtonUI.createUI(salesDetailsBtn));
         homeBtn.setUI((ButtonUI) BasicButtonUI.createUI(homeBtn));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        carWashBtn = new javax.swing.JButton();
        salesDetailsBtn = new javax.swing.JButton();
        storageBtn = new javax.swing.JButton();
        orderBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        employyeMenuBtn = new javax.swing.JMenu();
        employeeFrameBtn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        fuelSalesChartBtn = new javax.swing.JMenuItem();
        carWashChartBtn = new javax.swing.JMenuItem();
        engineTableBtn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        generateFuelSalesReport = new javax.swing.JMenuItem();
        carWashReport = new javax.swing.JMenuItem();
        aaaa = new javax.swing.JMenu();
        backUpBtn = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        logOutBtn = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        carWashBtn.setBackground(new java.awt.Color(34, 167, 240));
        carWashBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        carWashBtn.setForeground(new java.awt.Color(255, 255, 255));
        carWashBtn.setText("Car Wash Queue");
        carWashBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carWashBtnActionPerformed(evt);
            }
        });

        salesDetailsBtn.setBackground(new java.awt.Color(34, 167, 240));
        salesDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salesDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        salesDetailsBtn.setText("Sales Details");
        salesDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesDetailsBtnActionPerformed(evt);
            }
        });

        storageBtn.setBackground(new java.awt.Color(34, 167, 240));
        storageBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        storageBtn.setForeground(new java.awt.Color(255, 255, 255));
        storageBtn.setText("Storage Details");
        storageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storageBtnActionPerformed(evt);
            }
        });

        orderBtn.setBackground(new java.awt.Color(34, 167, 240));
        orderBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderBtn.setForeground(new java.awt.Color(255, 255, 255));
        orderBtn.setText("Order");
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(255, 51, 51));
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JustPump....");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                .addGap(193, 193, 193))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeBtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(salesDetailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(storageBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(carWashBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtn)
                .addGap(56, 56, 56)
                .addComponent(carWashBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(orderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(storageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(salesDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        employyeMenuBtn.setText("Employee");

        employeeFrameBtn.setText("Employee Frame");
        employeeFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeFrameBtnActionPerformed(evt);
            }
        });
        employyeMenuBtn.add(employeeFrameBtn);

        jMenuBar1.add(employyeMenuBtn);

        jMenu2.setText("Reports");

        jMenu4.setText("Generate Charts");

        fuelSalesChartBtn.setText("Fuel Sales Chart");
        fuelSalesChartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelSalesChartBtnActionPerformed(evt);
            }
        });
        jMenu4.add(fuelSalesChartBtn);

        carWashChartBtn.setText("CarWash Sales Chart");
        carWashChartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carWashChartBtnActionPerformed(evt);
            }
        });
        jMenu4.add(carWashChartBtn);

        engineTableBtn.setText("Engine Service Table");
        engineTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineTableBtnActionPerformed(evt);
            }
        });
        jMenu4.add(engineTableBtn);

        jMenu2.add(jMenu4);

        jMenu3.setText("Generate Reports");

        generateFuelSalesReport.setText("Fuel Sales Report");
        generateFuelSalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateFuelSalesReportActionPerformed(evt);
            }
        });
        jMenu3.add(generateFuelSalesReport);

        carWashReport.setText("CarWash Sales Report");
        carWashReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carWashReportActionPerformed(evt);
            }
        });
        jMenu3.add(carWashReport);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        aaaa.setText("Backup");

        backUpBtn.setText("Backup Files");
        backUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backUpBtnActionPerformed(evt);
            }
        });
        aaaa.add(backUpBtn);

        jMenuBar1.add(aaaa);

        jMenu1.setText("Exit");

        logOutBtn.setText("Log Out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        jMenu1.add(logOutBtn);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carWashBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carWashBtnActionPerformed
        carWashJ.setVisible(true);
        orderJ.setVisible(false);
        salesJ.setVisible(false);
        storageJ.setVisible(false);
    }//GEN-LAST:event_carWashBtnActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        carWashJ.setVisible(false);
        orderJ.setVisible(true);
        salesJ.setVisible(false);
        storageJ.setVisible(false);
    }//GEN-LAST:event_orderBtnActionPerformed

    private void storageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storageBtnActionPerformed
        carWashJ.setVisible(false);
        orderJ.setVisible(false);
        salesJ.setVisible(false);
        storageJ.setVisible(true);
    }//GEN-LAST:event_storageBtnActionPerformed

    private void salesDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesDetailsBtnActionPerformed
        carWashJ.setVisible(false);
        orderJ.setVisible(false);
        salesJ.setVisible(true);
        storageJ.setVisible(false);
    }//GEN-LAST:event_salesDetailsBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        MainFrame m = new MainFrame();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void employeeFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeFrameBtnActionPerformed
        EmployeeFrame e = new EmployeeFrame();
        e.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_employeeFrameBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        carWashJ.setVisible(false);
        orderJ.setVisible(false);
        salesJ.setVisible(false);
        storageJ.setVisible(false);
       
    }//GEN-LAST:event_homeBtnActionPerformed

    private void fuelSalesChartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelSalesChartBtnActionPerformed
       FuelSalesChartsFrame f = new FuelSalesChartsFrame();
       f.setVisible(true);
    }//GEN-LAST:event_fuelSalesChartBtnActionPerformed

    private void carWashChartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carWashChartBtnActionPerformed
       BodyWashSalesChartFrame b = new BodyWashSalesChartFrame();
       b.setVisible(true);
    }//GEN-LAST:event_carWashChartBtnActionPerformed

    private void engineTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineTableBtnActionPerformed
        EngineSalesChartFrame e = new EngineSalesChartFrame();
        e.setVisible(true);
    }//GEN-LAST:event_engineTableBtnActionPerformed

    private void backUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backUpBtnActionPerformed
        JFileChooser sc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("bin","txt");
        sc.setFileFilter(filter);
        sc.setCurrentDirectory(new File("C:\\COURSES\\CSC305 or CSE213\\Java Programs\\JFileChooser"));
        JFileChooser dc = new JFileChooser();       
        dc.setCurrentDirectory(new File("C:\\COURSES\\CSC305 or CSE213\\Java Programs\\JFileChooser"));
        int returnVal = sc.showOpenDialog(this);
        if (returnVal == sc.APPROVE_OPTION) {
            File source = sc.getSelectedFile();
            if (dc.showSaveDialog(this) == dc.APPROVE_OPTION) {
            try{
                File file = dc.getSelectedFile();
                File dest = new File(file.getAbsolutePath());
                try {
                FileUtils.copyFile(source, dest);
            } catch (IOException ex) {
                Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            catch(Exception e){}
        }                                        
        else{
            JOptionPane.showMessageDialog(null,"Operation Denied");
        }
         
        }
    }//GEN-LAST:event_backUpBtnActionPerformed

    private void generateFuelSalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateFuelSalesReportActionPerformed
        
        Document doc = new Document();
        
        try{
         PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream("FuelSalesReport.pdf"));
            doc.open();
            Image pieChartImage = Image.getInstance("fuelSalesPieChart.jpg");
            doc.add(pieChartImage);
            doc.add(new Paragraph("\n\n"));
            
            Image barChartImage = Image.getInstance("fuelSalesBarChart.jpg");
            doc.add(barChartImage);
            doc.add(new Paragraph("\n\n"));
            
            Image lineChartImage = Image.getInstance("fuelSalesLineChart.jpg");
            doc.add(lineChartImage);
            doc.add(new Paragraph("\n\n"));
            
            doc.close();
            JOptionPane.showMessageDialog(null,"Report Saved");
        }
        catch (FileNotFoundException ex){} 
        catch (DocumentException ex){} 
        catch (IOException ex){}
    
    }//GEN-LAST:event_generateFuelSalesReportActionPerformed

    private void carWashReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carWashReportActionPerformed
             
        Document doc = new Document();
        
        try{
         PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream("CarWashSalesReport.pdf"));
            doc.open();
            Image pieChartImage = Image.getInstance("CarWashSalesPieChart.jpg");
            doc.add(pieChartImage);
            doc.add(new Paragraph("\n\n"));
            
            Image barChartImage = Image.getInstance("CarWashSalesBarChart.jpg");
            doc.add(barChartImage);
            doc.add(new Paragraph("\n\n"));
            
            Image lineChartImage = Image.getInstance("CarWashSalesLineChart.jpg");
            doc.add(lineChartImage);
            doc.add(new Paragraph("\n\n"));
            
            doc.close();
            JOptionPane.showMessageDialog(null,"Report Saved");
        }
        catch (FileNotFoundException ex){} 
        catch (DocumentException ex){} 
        catch (IOException ex){}
    }//GEN-LAST:event_carWashReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</carWashInternalFrame       /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }
    ButtonGroup btn1 = new ButtonGroup ();
    CarWashInternalFrame carWashJ = new CarWashInternalFrame();
    OrderInternalFrame orderJ = new OrderInternalFrame();
    SalesInternalFrame salesJ = new SalesInternalFrame();
    StorageInternalFrame storageJ = new StorageInternalFrame();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aaaa;
    private javax.swing.JMenuItem backUpBtn;
    private javax.swing.JButton carWashBtn;
    private javax.swing.JMenuItem carWashChartBtn;
    private javax.swing.JMenuItem carWashReport;
    private javax.swing.JMenuItem employeeFrameBtn;
    private javax.swing.JMenu employyeMenuBtn;
    private javax.swing.JMenuItem engineTableBtn;
    private javax.swing.JMenuItem fuelSalesChartBtn;
    private javax.swing.JMenuItem generateFuelSalesReport;
    private javax.swing.JButton homeBtn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem logOutBtn;
    private javax.swing.JButton orderBtn;
    private javax.swing.JButton salesDetailsBtn;
    private javax.swing.JButton storageBtn;
    // End of variables declaration//GEN-END:variables
}
