/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpkg;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.plaf.ButtonUI;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;
import myclasses.Admin;
import myclasses.Customer;

/**
 *
 * @author Sadman's Den
 */
public class BodywashFrame extends javax.swing.JFrame {

    /**
     * Creates new form BodywashFrame
     */
    Customer activeUser = null;
    Admin admin = new Admin();

    public BodywashFrame(Customer c) {
        initComponents();
        activeUser = c;
        btn.add(fullWashRadioButton);
        btn.add(innerWashRadioButton);
        btn.add(outerWashRadioButton);
        btn.add(specialWashRadioButton);
        bookBtn.setUI((ButtonUI) BasicButtonUI.createUI(bookBtn));
        homeBtn.setUI((ButtonUI) BasicButtonUI.createUI(homeBtn));
        this.setLocationRelativeTo(null);
         datePicker.setFormats("dd/MM/yyyy");
    }

    public BodywashFrame() {
        initComponents();
        btn.add(fullWashRadioButton);
        btn.add(innerWashRadioButton);
        btn.add(outerWashRadioButton);
        btn.add(specialWashRadioButton);
        bookBtn.setUI((ButtonUI) BasicButtonUI.createUI(bookBtn));
        homeBtn.setUI((ButtonUI) BasicButtonUI.createUI(homeBtn));
        this.setLocationRelativeTo(null);
        datePicker.setFormats("dd/MM/yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bookBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        timeBox = new javax.swing.JComboBox<String>();
        priceTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fullWashRadioButton = new javax.swing.JRadioButton();
        innerWashRadioButton = new javax.swing.JRadioButton();
        outerWashRadioButton = new javax.swing.JRadioButton();
        specialWashRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        homeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 62, 80));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        bookBtn.setBackground(new java.awt.Color(34, 167, 240));
        bookBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookBtn.setText("Book Now");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select Time :");

        timeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10:00", "11:00", "12:00", "1:00", "2:00", "3:00", "4:00" }));

        priceTxt.setBackground(new java.awt.Color(108, 122, 107));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price (BDT) :");

        fullWashRadioButton.setBackground(new java.awt.Color(44, 62, 80));
        fullWashRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        fullWashRadioButton.setText("Full Wash");
        fullWashRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullWashRadioButtonActionPerformed(evt);
            }
        });

        innerWashRadioButton.setBackground(new java.awt.Color(44, 62, 80));
        innerWashRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        innerWashRadioButton.setText("Inner Wash");
        innerWashRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                innerWashRadioButtonActionPerformed(evt);
            }
        });

        outerWashRadioButton.setBackground(new java.awt.Color(44, 62, 80));
        outerWashRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        outerWashRadioButton.setText("Outer Wash");
        outerWashRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outerWashRadioButtonActionPerformed(evt);
            }
        });

        specialWashRadioButton.setBackground(new java.awt.Color(44, 62, 80));
        specialWashRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        specialWashRadioButton.setText("Special Wash");
        specialWashRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialWashRadioButtonActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Wash Type :");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter ID :");

        idTxt.setBackground(new java.awt.Color(108, 122, 107));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(fullWashRadioButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(innerWashRadioButton)
                                    .addComponent(timeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(outerWashRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(specialWashRadioButton))
                                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullWashRadioButton)
                    .addComponent(innerWashRadioButton)
                    .addComponent(outerWashRadioButton)
                    .addComponent(specialWashRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(timeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        homeBtn.setBackground(new java.awt.Color(255, 51, 51));
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(homeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(homeBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
           int id = Integer.parseInt(idTxt.getText());
            float price=0;
            String type = "";
            if(fullWashRadioButton.isSelected()){
                price = 1000; type = "FullWash";
            }
            else if(innerWashRadioButton.isSelected()){
                price = 700;   type = "InnerWash"; 
            }
            else if(outerWashRadioButton.isSelected()){
                price = 500;   type = "OuterWash";
            }
            else if(specialWashRadioButton.isSelected()){
                price = 1500;  type = "SpecialWash";
            }
            
            String str = idTxt.getText() + "," + type + "," + price + "," + timeBox.getSelectedItem()+ "," +datePicker.getDate() ;
            String curr = timeBox.getSelectedItem()+ "," +datePicker.getDate() ;
             try{
          
            FileWriter fw = null;
            File file = new File ("CarWashList.txt");
            if (!file.exists ()){ 
                fw = new FileWriter("CarWashList.txt");
                fw.write(str);
                fw.close();
                JOptionPane.showMessageDialog(null, "Booking is done");
                activeUser.payBill(price);
            }
            
            else {
             ArrayList<String> list = new ArrayList();
             boolean invalid = false;
             Scanner sc = new Scanner (file);
             while(sc.hasNextLine()){
                 list.add(sc.nextLine());
             }
             for(String x : list){
                 String[] ss = x.split(",");
                 if(curr.equals(ss[3]+","+ss[4])) invalid = true;
             }
             if(invalid == true){ JOptionPane.showMessageDialog(null, "Time SLot Is TAKEN!!!");  }
             else{
                 fw = new FileWriter("CarWashList.txt",true);
                 BufferedWriter br = new BufferedWriter(fw);
                 br.newLine();
                 br.write(str);
                 br.close();
                 JOptionPane.showMessageDialog(null, "Booking is done");
                 activeUser.payBill(price);
                }
            }
        }
        catch(Exception e){} 
    }//GEN-LAST:event_bookBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        customerFrame c = new customerFrame(activeUser);
        c.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_homeBtnActionPerformed

    private void fullWashRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullWashRadioButtonActionPerformed
        priceTxt.setText("1000");
    }//GEN-LAST:event_fullWashRadioButtonActionPerformed

    private void innerWashRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_innerWashRadioButtonActionPerformed
        priceTxt.setText("700");
    }//GEN-LAST:event_innerWashRadioButtonActionPerformed

    private void outerWashRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outerWashRadioButtonActionPerformed
        priceTxt.setText("500");
    }//GEN-LAST:event_outerWashRadioButtonActionPerformed

    private void specialWashRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialWashRadioButtonActionPerformed
        priceTxt.setText("1500");
    }//GEN-LAST:event_specialWashRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BodywashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BodywashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BodywashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BodywashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BodywashFrame().setVisible(true);
            }
        });
    }
    ButtonGroup btn = new ButtonGroup();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBtn;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JRadioButton fullWashRadioButton;
    private javax.swing.JButton homeBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JRadioButton innerWashRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton outerWashRadioButton;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JRadioButton specialWashRadioButton;
    private javax.swing.JComboBox<String> timeBox;
    // End of variables declaration//GEN-END:variables
}
