/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpkg;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.ButtonUI;
import javax.swing.plaf.basic.BasicButtonUI;
import myclasses.Customer;
import myclasses.Fuel;

/**
 *
 * @author Sadman's Den
 */
public class BuyFrame extends javax.swing.JFrame {

    /**
     * Creates new form BuyFrame
     */
    
        Customer activeUser = null;

        public BuyFrame(Customer c) {
        initComponents();
        activeUser = c;

        userComboBox.setSelectedIndex(0);
        priceTxt.setText("85");
         btn.add(literRadioButton);
         btn.add(tkRadioButton);
         buyAndShowBillBtn.setUI((ButtonUI) BasicButtonUI.createUI(buyAndShowBillBtn));
         homeBtn.setUI((ButtonUI) BasicButtonUI.createUI(homeBtn));
         this.setLocationRelativeTo(null);

    }

    
    public BuyFrame() {
        initComponents();
        userComboBox.setSelectedIndex(0);
        priceTxt.setText("85");
         btn.add(literRadioButton);
         btn.add(tkRadioButton);
         buyAndShowBillBtn.setUI((ButtonUI) BasicButtonUI.createUI(buyAndShowBillBtn));
         homeBtn.setUI((ButtonUI) BasicButtonUI.createUI(homeBtn));
         this.setLocationRelativeTo(null);
         
    }
    
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        buyAndShowBillBtn = new javax.swing.JButton();
        amountTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        userComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tkRadioButton = new javax.swing.JRadioButton();
        literRadioButton = new javax.swing.JRadioButton();
        priceTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        buyAndShowBillBtn.setBackground(new java.awt.Color(34, 167, 240));
        buyAndShowBillBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buyAndShowBillBtn.setForeground(new java.awt.Color(255, 255, 255));
        buyAndShowBillBtn.setText("Buy and show bill");
        buyAndShowBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyAndShowBillBtnActionPerformed(evt);
            }
        });

        amountTxt.setBackground(new java.awt.Color(108, 122, 107));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Amount/Quantity Below: ");

        userComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petrol", "Octane", "Diesel", "Kerosene" }));
        userComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Select Buy method: ");

        tkRadioButton.setBackground(new java.awt.Color(44, 62, 80));
        tkRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tkRadioButton.setText("Taka");

        literRadioButton.setBackground(new java.awt.Color(44, 62, 80));
        literRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        literRadioButton.setText("Liter");

        priceTxt.setBackground(new java.awt.Color(108, 122, 107));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Price (BDT) :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyAndShowBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(literRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tkRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(amountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tkRadioButton)
                        .addGap(0, 0, 0)
                        .addComponent(literRadioButton))
                    .addComponent(amountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(buyAndShowBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        homeBtn.setBackground(new java.awt.Color(255, 51, 51));
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(homeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeBtn)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyAndShowBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyAndShowBillBtnActionPerformed
 
        File file = new File("FuelSalesList.txt");
        File file2 = new File("myTempFuelSalesList.txt");
            BufferedWriter bw = null;
            try {
                if(!file.exists()) bw = new BufferedWriter(new FileWriter(file));
                else  {
                bw = new BufferedWriter(new FileWriter("FuelSalesList.txt",true));
                }
            }   
            catch (IOException ex) {
                Logger.getLogger(BuyFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            BufferedWriter bw2 = null;
            try {
                if(!file2.exists()) bw2 = new BufferedWriter(new FileWriter(file2));
                else  {
                bw2 = new BufferedWriter(new FileWriter("myTempFuelSalesList.txt",true));
                }
            }   
            catch (IOException ex) {
                Logger.getLogger(BuyFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        int fuelPrice = Integer.parseInt(priceTxt.getText());
        float totalPrice = 0 ;
        int value;
        int amount = Integer.parseInt(amountTxt.getText());
        if(literRadioButton.isSelected()){
            totalPrice = fuelPrice*amount;
            value = JOptionPane.showConfirmDialog(null, "Your Bill is : "+ totalPrice);
            if(value == 0){
                activeUser.buyFuel(totalPrice);
             try {
             bw.write(activeUser.getId()+","+userComboBox.getSelectedItem()+","+totalPrice+","+amount);bw2.write(activeUser.getId()+","+userComboBox.getSelectedItem()+","+totalPrice+","+amount);
             bw.newLine();bw2.newLine();
             bw.close();bw2.close();
         }  catch (IOException ex) {
             Logger.getLogger(BuyFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
            }
        }
        else if(tkRadioButton.isSelected()){
            totalPrice = amount;
            value = JOptionPane.showConfirmDialog(null, "Your Bill is : "+ totalPrice);
            if(value == 0){
                activeUser.buyFuel(totalPrice);
            try {
                float a = totalPrice/fuelPrice;
                bw.write(activeUser.getId()+","+userComboBox.getSelectedItem()+","+totalPrice+","+a);bw2.write(activeUser.getId()+","+userComboBox.getSelectedItem()+","+totalPrice+","+a);
                bw.newLine(); bw2.newLine();
                bw.close(); bw2.close();
         } catch (IOException ex) {
             Logger.getLogger(BuyFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
            }
        }

    }//GEN-LAST:event_buyAndShowBillBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        customerFrame c = new customerFrame(activeUser);
        c.setVisible(true);
        this.dispose(); 
        
    }//GEN-LAST:event_homeBtnActionPerformed

    private void userComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userComboBoxActionPerformed
        if(userComboBox.getSelectedItem().equals("Petrol")){
                priceTxt.setText("80");
        }
        if(userComboBox.getSelectedItem().equals("Octane")){
                priceTxt.setText("90");
        }
        if(userComboBox.getSelectedItem().equals("Diesel")){
                priceTxt.setText("55");
        }
        if(userComboBox.getSelectedItem().equals("Kerosene")){
                priceTxt.setText("45");
        }
    }//GEN-LAST:event_userComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyFrame().setVisible(true);
            }
        });
    }
    
      ButtonGroup btn = new ButtonGroup();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTxt;
    private javax.swing.JButton buyAndShowBillBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton literRadioButton;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JRadioButton tkRadioButton;
    private javax.swing.JComboBox<String> userComboBox;
    // End of variables declaration//GEN-END:variables
}
