/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpkg;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.plaf.ButtonUI;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;
import myclasses.Admin;

/**
 *
 * @author Sadman's Den
 */
public class CarWashInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form CarWashInternalFrame
     */
    Admin admin = new Admin();
    public CarWashInternalFrame() {
        initComponents();
        approveBtn.setUI((ButtonUI) BasicButtonUI.createUI(approveBtn));
        loadCarWashTableBtn.setUI((ButtonUI) BasicButtonUI.createUI(loadCarWashTableBtn));
        btn.add(jRadioButton1);
        btn.add(jRadioButton2);
        btn.add(jRadioButton3);
        btn.add(jRadioButton4);
        
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carWashTable = new javax.swing.JTable();
        approveBtn = new javax.swing.JButton();
        loadCarWashTableBtn = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        jRadioButton3.setText("jRadioButton3");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(559, 467));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Car Wash Queue : ");

        carWashTable.setBackground(new java.awt.Color(108, 122, 107));
        carWashTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Selected", "ID", "Type", "Bill", "Time", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(carWashTable);

        approveBtn.setBackground(new java.awt.Color(34, 167, 240));
        approveBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        approveBtn.setText("Approve");
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        loadCarWashTableBtn.setBackground(new java.awt.Color(255, 51, 51));
        loadCarWashTableBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loadCarWashTableBtn.setText("Load Sales Table");
        loadCarWashTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadCarWashTableBtnActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(44, 62, 80));
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Station 1");

        jRadioButton2.setBackground(new java.awt.Color(44, 62, 80));
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Station 2");

        jRadioButton4.setBackground(new java.awt.Color(44, 62, 80));
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Station 3");

        jRadioButton5.setBackground(new java.awt.Color(44, 62, 80));
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Station 4");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Station:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(loadCarWashTableBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(114, 114, 114)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton5)))
                                .addGap(13, 13, 13))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(loadCarWashTableBtn)))
                        .addGap(25, 25, 25)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadCarWashTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadCarWashTableBtnActionPerformed
           Scanner s = null;
        try {
            s = new Scanner(new File("CarWashList.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CarWashInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           while (s.hasNextLine()){
                admin.getCarWashList().add(s.nextLine());
            }
            s.close();
             for(String str :admin.getCarWashList()){
                 String[] ss = str.split(",");
                 DefaultTableModel dm = new DefaultTableModel();
                 dm = (DefaultTableModel)carWashTable.getModel();
                 dm.addRow(new Object[]{ false, ss[0], ss[1], ss[2],ss[3],ss[4]});
             }
    }//GEN-LAST:event_loadCarWashTableBtnActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
       File inputFile = new File("CarWashList.txt");
       File tempFile = new File("myTempFile.txt");
       File salesFile = new File("BodyWashSalesList.txt");
       
       BufferedWriter salesWriter = null;
        try {
            if(!salesFile.exists())salesWriter = new BufferedWriter(new FileWriter(salesFile));
            else  {
               // FileWriter fw = new FileWriter(salesFile,true);
                salesWriter = new BufferedWriter(new FileWriter(salesFile,true));
            }
        } catch (IOException ex) {
            Logger.getLogger(CarWashInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    BufferedReader reader = null;
        try {
            reader = new BufferedReader(new FileReader(inputFile));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CarWashInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    BufferedWriter writer = null;
        try {
           writer = new BufferedWriter(new FileWriter(tempFile));
        } catch (IOException ex) {
            Logger.getLogger(CarWashInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    int rowCount = carWashTable.getRowCount();
    
    ArrayList<String> lineToRemove = new ArrayList();
    String currentLine;
    for(int i = 0 ; i<rowCount; i++){
        boolean approved;
        approved = (boolean)carWashTable.getModel().getValueAt(i, 0);
        if (approved == true) {
           String ss; 
           ss = carWashTable.getModel().getValueAt(i, 1) + "," + carWashTable.getModel().getValueAt(i,2) + "," + carWashTable.getModel().getValueAt(i, 3) + "," + carWashTable.getModel().getValueAt(i, 4)+ "," + carWashTable.getModel().getValueAt(i, 5);
           lineToRemove.add(ss);
          // System.out.println(ss);
        }
    }    
        System.out.println("");
        ArrayList<String> newLines = new ArrayList();
        ArrayList<String> salesList = new ArrayList();
        Scanner s = null;
        try {
            s = new Scanner(new File("CarWashList.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CarWashInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           while (s.hasNextLine()){
               boolean valid = true;
               String ww = s.nextLine();
               for(String arr : lineToRemove){
               if(ww.equals(arr)) {
                  valid = false;
                }
               }
            if(valid==true) newLines.add(ww);
            else salesList.add(ww);
           }
           for(String sww : salesList )System.out.println(sww);
           s.close();
          for(String a : newLines){
           try {
               writer.flush();
               writer.write(a);
               writer.newLine();
           } catch (IOException ex) {
               Logger.getLogger(CarWashInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
           }
          }
            for(String a : salesList){
           try {
               salesWriter.flush();
               salesWriter.write(a);
               salesWriter.newLine();
           } catch (IOException ex) {
               Logger.getLogger(CarWashInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
           }
          }
          
        try {
            salesWriter.close();
            writer.close();
            reader.close();
        } catch (IOException ex) {
            Logger.getLogger(CarWashInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        if(inputFile.delete()) 
        { 
            //System.out.println(inputFile.getName() + "File deleted successfully"); 
        } 
        else
        { 
           // System.out.println(inputFile.getName() +"Failed to delete the file"); 
        } 
        boolean successful = tempFile.renameTo(inputFile);
        
        
        admin.getCarWashList().clear();
        
        DefaultTableModel m = new DefaultTableModel();
        m = (DefaultTableModel)carWashTable.getModel();
        m.setRowCount(0);
        Scanner sc = null;
        try {
            sc = new Scanner(new File("CarWashList.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CarWashInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           while (sc.hasNextLine()){
                admin.getCarWashList().add(sc.nextLine());
            }
            sc.close();
             for(String str :admin.getCarWashList()){
                 String[] ss = str.split(",");
                 DefaultTableModel dm = new DefaultTableModel();
                 dm = (DefaultTableModel)carWashTable.getModel();
                 dm.addRow(new Object[]{ false, ss[0], ss[1], ss[2],ss[3],ss[4]});
             }
        if(inputFile.length()<1)
        {
        boolean successs=inputFile.delete();
            }
    }//GEN-LAST:event_approveBtnActionPerformed

    ButtonGroup btn = new ButtonGroup();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JTable carWashTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadCarWashTableBtn;
    // End of variables declaration//GEN-END:variables
}
