/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpkg;

import javax.swing.JFrame;
import myclasses.Customer;

/**
 *
 * @author Sadman's Den
 */
public class CustomerAccountFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerAccountFrame
     */
    Customer user = null;
    
    public CustomerAccountFrame(Customer activeUser) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        
        user = activeUser;
        nameLb.setText(user.name);
        idLb.setText(Integer.toString(user.getId()));
        passwordLb.setText(user.getPassword());
        genderLb.setText(user.gender);
        accountNameLb.setText(user.getAccount().accountName);
        accountNoLb.setText(user.getAccount().accountNo);
        creditCardLb.setText(user.getAccount().cardNo);
        nidLb.setText(user.getAccount().nidNo);
        balanceLb.setText(Float.toString(user.getAccount().balance));
        
    }
    
    public CustomerAccountFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        accountName = new javax.swing.JLabel();
        accountNo = new javax.swing.JLabel();
        creditCard = new javax.swing.JLabel();
        nid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLb = new javax.swing.JLabel();
        passwordLb = new javax.swing.JLabel();
        genderLb = new javax.swing.JLabel();
        accountNameLb = new javax.swing.JLabel();
        accountNoLb = new javax.swing.JLabel();
        creditCardLb = new javax.swing.JLabel();
        nidLb = new javax.swing.JLabel();
        balanceLb = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        idLb = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Name :");

        name1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setText("Password:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gender :");

        accountName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accountName.setForeground(new java.awt.Color(255, 255, 255));
        accountName.setText("Account Name :");

        accountNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accountNo.setForeground(new java.awt.Color(255, 255, 255));
        accountNo.setText("Account No :");

        creditCard.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCard.setForeground(new java.awt.Color(255, 255, 255));
        creditCard.setText("Credit Card No :");

        nid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nid.setForeground(new java.awt.Color(255, 255, 255));
        nid.setText("NID No :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Balance :");

        nameLb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameLb.setForeground(new java.awt.Color(255, 255, 255));

        passwordLb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordLb.setForeground(new java.awt.Color(255, 255, 255));

        genderLb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        genderLb.setForeground(new java.awt.Color(255, 255, 255));

        accountNameLb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accountNameLb.setForeground(new java.awt.Color(255, 255, 255));

        accountNoLb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accountNoLb.setForeground(new java.awt.Color(255, 255, 255));

        creditCardLb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        creditCardLb.setForeground(new java.awt.Color(255, 255, 255));

        nidLb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nidLb.setForeground(new java.awt.Color(255, 255, 255));

        balanceLb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        balanceLb.setForeground(new java.awt.Color(255, 255, 255));

        name2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name2.setForeground(new java.awt.Color(255, 255, 255));
        name2.setText("ID :");

        idLb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idLb.setForeground(new java.awt.Color(255, 255, 255));

        name3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name3.setForeground(new java.awt.Color(255, 255, 255));
        name3.setText("Account Details:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nid, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name)
                                    .addComponent(name1)
                                    .addComponent(jLabel1)
                                    .addComponent(accountName)
                                    .addComponent(accountNo)
                                    .addComponent(creditCard)
                                    .addComponent(jLabel2)
                                    .addComponent(name2))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idLb, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(balanceLb, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(creditCardLb, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accountNoLb, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accountNameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderLb, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordLb, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nidLb, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(name3)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name3)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(nameLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name2)
                    .addComponent(idLb))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1)
                    .addComponent(passwordLb))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(genderLb))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountName)
                    .addComponent(accountNameLb))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNo)
                    .addComponent(accountNoLb))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditCard)
                    .addComponent(creditCardLb))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nid)
                    .addComponent(nidLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(balanceLb))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerAccountFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountName;
    private javax.swing.JLabel accountNameLb;
    private javax.swing.JLabel accountNo;
    private javax.swing.JLabel accountNoLb;
    private javax.swing.JLabel balanceLb;
    private javax.swing.JLabel creditCard;
    private javax.swing.JLabel creditCardLb;
    private javax.swing.JLabel genderLb;
    private javax.swing.JLabel idLb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel nameLb;
    private javax.swing.JLabel nid;
    private javax.swing.JLabel nidLb;
    private javax.swing.JLabel passwordLb;
    // End of variables declaration//GEN-END:variables
}
