/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpkg;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.ButtonUI;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sadman's Den
 */
public class OrderInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form OrderInternalFrame
     */
    public OrderInternalFrame() {
        initComponents();
        btn.add(dieselRadioButton);
        btn.add(keroseneRadioButton);
        btn.add(octaneRadioButton);
        btn.add(petrolRadioButton);
        sendOrderBtn.setUI((ButtonUI) BasicButtonUI.createUI(sendOrderBtn));
        addTableBtn.setUI((ButtonUI) BasicButtonUI.createUI(addTableBtn));
        removeBtn.setUI((ButtonUI) BasicButtonUI.createUI(addTableBtn));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sendOrderBtn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        addTableBtn = new javax.swing.JButton();
        quantityTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        petrolRadioButton = new javax.swing.JRadioButton();
        octaneRadioButton = new javax.swing.JRadioButton();
        dieselRadioButton = new javax.swing.JRadioButton();
        keroseneRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        removeBtn = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        addSupplierTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        sendOrderBtn.setBackground(new java.awt.Color(34, 167, 240));
        sendOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sendOrderBtn.setText("Send Order");
        sendOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendOrderBtnActionPerformed(evt);
            }
        });

        orderTable.setBackground(new java.awt.Color(108, 122, 107));
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order No.", "Supplier ID", "Type", "Quantity"
            }
        ));
        jScrollPane6.setViewportView(orderTable);

        addTableBtn.setBackground(new java.awt.Color(255, 51, 51));
        addTableBtn.setText("Add to Table");
        addTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTableBtnActionPerformed(evt);
            }
        });

        quantityTxt.setBackground(new java.awt.Color(108, 122, 107));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Quantity (liter):");

        petrolRadioButton.setBackground(new java.awt.Color(44, 62, 80));
        petrolRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        petrolRadioButton.setText("Petrol");

        octaneRadioButton.setBackground(new java.awt.Color(44, 62, 80));
        octaneRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        octaneRadioButton.setText("Octane");

        dieselRadioButton.setBackground(new java.awt.Color(44, 62, 80));
        dieselRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        dieselRadioButton.setText("Diesel");

        keroseneRadioButton.setBackground(new java.awt.Color(44, 62, 80));
        keroseneRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        keroseneRadioButton.setText("Kerosene");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select Type :");

        removeBtn.setBackground(new java.awt.Color(255, 51, 51));
        removeBtn.setText("Remove order from Table");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0000", "2222" }));

        jButton1.setText("Add Supplier:");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(petrolRadioButton)
                        .addGap(45, 45, 45)
                        .addComponent(octaneRadioButton)
                        .addGap(35, 35, 35)
                        .addComponent(dieselRadioButton)
                        .addGap(42, 42, 42)
                        .addComponent(keroseneRadioButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sendOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeBtn)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addTableBtn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addSupplierTxt)
                            .addComponent(ComboBox, 0, 94, Short.MAX_VALUE))
                        .addGap(53, 53, 53))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petrolRadioButton)
                    .addComponent(octaneRadioButton)
                    .addComponent(dieselRadioButton)
                    .addComponent(keroseneRadioButton))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSupplierTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTableBtn)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeBtn)
                .addGap(28, 28, 28)
                .addComponent(sendOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTableBtnActionPerformed

        DefaultTableModel dm = new DefaultTableModel();
        dm = (DefaultTableModel)orderTable.getModel();
        String type = null;
        Float quantity = Float.parseFloat(quantityTxt.getText());
        if(dieselRadioButton.isSelected()) type = "Diesel";
        if(octaneRadioButton.isSelected()) type = "Octane";
        if(petrolRadioButton.isSelected()) type = "Petrol";
        if(keroseneRadioButton.isSelected()) type = "Kerosene";
        dm.addRow(new Object[]{c+1,ComboBox.getSelectedItem(),type,quantity});
        c++;
    }//GEN-LAST:event_addTableBtnActionPerformed

    private void sendOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendOrderBtnActionPerformed
        File file = new File ("OrderList.txt");
        BufferedWriter bw = null;
        try {
            if(!file.exists())bw = new BufferedWriter(new FileWriter(file));
            
            else {
                bw = new BufferedWriter(new FileWriter(file,true));
            }
        } catch (IOException ex) {
            Logger.getLogger(OrderInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int rowCount = orderTable.getRowCount();
        for(int i=0; i<rowCount; i++){
            String ss = orderTable.getValueAt(i, 1)+ "," +"1730451"+ "," + orderTable.getValueAt(i, 2)+ "," +orderTable.getValueAt(i, 3);
            try {
                bw.write(ss);
                bw.newLine();
            } catch (IOException ex) {
                Logger.getLogger(OrderInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(OrderInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel m = new DefaultTableModel();
        m = (DefaultTableModel)orderTable.getModel();
        m.setRowCount(0);
        c=0;
        JOptionPane.showMessageDialog(null, "Order has been sent.");
    }//GEN-LAST:event_sendOrderBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        int no;
        no = Integer.parseInt(JOptionPane.showInputDialog("Enter Order NO:"));
        DefaultTableModel m = new DefaultTableModel();
        m = (DefaultTableModel)orderTable.getModel();
        m.removeRow(no-1);
    }//GEN-LAST:event_removeBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
       dm.addElement(addSupplierTxt.getText());
       ComboBox.setModel(dm);
    }//GEN-LAST:event_jButton1ActionPerformed
    int c =0;
    ButtonGroup btn = new ButtonGroup();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBox;
    private javax.swing.JTextField addSupplierTxt;
    private javax.swing.JButton addTableBtn;
    private javax.swing.JRadioButton dieselRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JRadioButton keroseneRadioButton;
    private javax.swing.JRadioButton octaneRadioButton;
    private javax.swing.JTable orderTable;
    private javax.swing.JRadioButton petrolRadioButton;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton sendOrderBtn;
    // End of variables declaration//GEN-END:variables
}
