/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpkg;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.ButtonUI;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sadman's Den
 */
public class SalesInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form SalesInternalFrame
     */
    public SalesInternalFrame() {
        initComponents();
        loadSalesTableBtn.setUI((ButtonUI) BasicButtonUI.createUI(loadSalesTableBtn));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        loadSalesTableBtn = new javax.swing.JButton();
        typeBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(559, 467));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        salesTable.setBackground(new java.awt.Color(108, 122, 107));
        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Type", "Sale (tk)"
            }
        ));
        jScrollPane5.setViewportView(salesTable);

        loadSalesTableBtn.setBackground(new java.awt.Color(255, 51, 51));
        loadSalesTableBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loadSalesTableBtn.setText("Load Sales Table");
        loadSalesTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSalesTableBtnActionPerformed(evt);
            }
        });

        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuel", "BodyWash" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadSalesTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loadSalesTableBtn)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadSalesTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSalesTableBtnActionPerformed
       String user = (String)typeBox.getSelectedItem();
       ArrayList<String> list = new ArrayList();
       if(user.equals("Fuel")){
               Scanner s = null;
        try {
            s = new Scanner(new File("FuelSalesList.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CarWashInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           while (s.hasNextLine()){
                list.add(s.nextLine());
            }
            s.close();
          for(String str : list){
                 String[] ss = str.split(",");
                 DefaultTableModel dm = new DefaultTableModel();
                 dm = (DefaultTableModel)salesTable.getModel();
                 dm.addRow(new Object[]{ss[0], ss[1], ss[2]});
             }  
            
       }
       
         if(user.equals("BodyWash")){
               Scanner s = null;
        try {
            s = new Scanner(new File("BodyWashSalesList.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CarWashInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           while (s.hasNextLine()){
                list.add(s.nextLine());
            }
            s.close();
          for(String str : list){
                 String[] ss = str.split(",");
                 DefaultTableModel dm = new DefaultTableModel();
                 dm = (DefaultTableModel)salesTable.getModel();
                 dm.addRow(new Object[]{ss[0], ss[1], ss[2]});
             }  
            
       }
    }//GEN-LAST:event_loadSalesTableBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton loadSalesTableBtn;
    private javax.swing.JTable salesTable;
    private javax.swing.JComboBox<String> typeBox;
    // End of variables declaration//GEN-END:variables
}
